
language: python
python:
 - "3.7"
install:
 - pip install -r requirements.txt
script:
 - python -m unittest test_user_model.py
 - python -m unittest test_user_views.py
 - python -m unittest test_message_model.py
 - python -m unittest test_message_views.py


